import { Router } from "express";
import { listTemplates, createTemplate, updateTemplate, deleteTemplate, createInstance, submitChecklist, reviewChecklist, getDailyChecklists, getPendingReviews, downloadPDF, uploadPhotoOCR } from "../controllers/checklist.controller";
import { authMiddleware } from "../middlewares/auth.middleware";
export const checklistRouter = Router();
checklistRouter.get("/templates", authMiddleware, listTemplates);
checklistRouter.post("/templates", authMiddleware, createTemplate);
checklistRouter.put("/templates/:id", authMiddleware, updateTemplate);
checklistRouter.delete("/templates/:id", authMiddleware, deleteTemplate);
checklistRouter.post("/instances", authMiddleware, createInstance);
checklistRouter.patch("/instances/:id/submit", authMiddleware, submitChecklist);
checklistRouter.patch("/instances/:id/review", authMiddleware, reviewChecklist);
checklistRouter.get("/daily", authMiddleware, getDailyChecklists);
checklistRouter.get("/pending-reviews", authMiddleware, getPendingReviews);
checklistRouter.get("/instances/:id/pdf", authMiddleware, downloadPDF);
checklistRouter.post("/ocr-upload", authMiddleware, uploadPhotoOCR);
